-- Copyright 2021-2023 Salvatore Barone <salvatore.barone@unina.it>
-- 
-- This file has been auto-generated by pyALS-rf
-- https://github.com/SalvatoreBarone/pyALS-rf 
-- 
-- This is free software; you can redistribute it and/or modify it under
-- the terms of the GNU General Public License as published by the Free
-- Software Foundation; either version 3 of the License, or any later version.
-- 
-- This is distributed in the hope that it will be useful, but WITHOUT
-- ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
-- FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
-- more details.
-- 
-- You should have received a copy of the GNU General Public License along with
-- RMEncoder; if not, write to the Free Software Foundation, Inc., 51 Franklin
-- Street, Fifth Floor, Boston, MA 02110-1301, USA.

library ieee;
use ieee.std_logic_1164.all;
entity swapper_block is
    generic (data_width : natural);
    port (
        data_in  : in std_logic_vector(data_width-1 downto 0);
        data_out : out std_logic_vector(data_width-1 downto 0));
end entity;
architecture dataflow of swapper_block is
    signal intermediate_data : std_logic_vector(data_width-1 downto 0) := (others => '0');
begin
    intermediate_data(0) <= data_in(0);
     
    odd_stage_swappers : for i in 0 to (data_width-1)/2-1 generate
       intermediate_data(2*i+1) <= data_in(2*i+1) or data_in(2*i+2);
       intermediate_data(2*i+2) <= data_in(2*i+1) and data_in(2*i+2);
    end generate;
    last_pass_through_1st : if data_width mod 2 = 0 generate
        intermediate_data(data_width-1) <= data_in(data_width-1);
    end generate;
    
    even_stage_swappers : for i in 0 to data_width/2-1 generate
         data_out(2*i) <= intermediate_data(2*i) or intermediate_data(2*i+1);
         data_out(2*i+1) <= intermediate_data(2*i) and intermediate_data(2*i+1);
      end generate;
    last_pass_through_2st : if data_width mod 2 = 1 generate
      data_out(data_width-1) <= intermediate_data(data_width-1);
      end generate;

end dataflow;
