#!/bin/bash
[ ! -d ./edginess_shared ] && mkdir ./edginess_shared
xhost local:docker
docker run --rm -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix -v $PWD/edginess_shared:/root/shared  -v $PWD/../:/root/EDGINESS-DBG -w /root --privileged -it edginess-docker /bin/zsh
